<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Confidence Intervals via Bootstrapping | Introduction to Statistical Methodology, Second Edition</title>
  <meta name="description" content="Chapter 3 Confidence Intervals via Bootstrapping | Introduction to Statistical Methodology, Second Edition" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Confidence Intervals via Bootstrapping | Introduction to Statistical Methodology, Second Edition" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="dereksonderegger/570" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Confidence Intervals via Bootstrapping | Introduction to Statistical Methodology, Second Edition" />
  
  
  

<meta name="author" content="Derek L. Sonderegger &amp; Robert Buscaglia" />


<meta name="date" content="2020-08-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="2-probability.html"/>
<link rel="next" href="4-sampling-distribution-of-barx.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html"><i class="fa fa-check"></i><b>1</b> Summary Statistics and Graphing</a><ul>
<li class="chapter" data-level="1.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#variable-types"><i class="fa fa-check"></i><b>1.1</b> Variable Types</a><ul>
<li class="chapter" data-level="1.1.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#categorical"><i class="fa fa-check"></i><b>1.1.1</b> Categorical</a></li>
<li class="chapter" data-level="1.1.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#numerical"><i class="fa fa-check"></i><b>1.1.2</b> Numerical</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#randomization-and-sampling"><i class="fa fa-check"></i><b>1.2</b> Randomization and Sampling</a><ul>
<li class="chapter" data-level="1.2.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#sampling-techniques"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Techniques</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#graphical-summaries"><i class="fa fa-check"></i><b>1.3</b> Graphical Summaries</a><ul>
<li class="chapter" data-level="1.3.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#barchartsbarplots-univariate---categorical"><i class="fa fa-check"></i><b>1.3.1</b> Barcharts/Barplots (Univariate - Categorical)</a></li>
<li class="chapter" data-level="1.3.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#histogram-univariate---numerical"><i class="fa fa-check"></i><b>1.3.2</b> Histogram (Univariate - Numerical)</a></li>
<li class="chapter" data-level="1.3.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#boxplot-bivariate---categorical-vs-numerical"><i class="fa fa-check"></i><b>1.3.3</b> Boxplot (Bivariate - Categorical vs Numerical)</a></li>
<li class="chapter" data-level="1.3.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#scatterplot-bivariate---numerical-vs-numerical"><i class="fa fa-check"></i><b>1.3.4</b> Scatterplot (Bivariate - Numerical vs Numerical)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#measures-of-centrality"><i class="fa fa-check"></i><b>1.4</b> Measures of Centrality</a><ul>
<li class="chapter" data-level="1.4.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#mean"><i class="fa fa-check"></i><b>1.4.1</b> Mean</a></li>
<li class="chapter" data-level="1.4.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#median"><i class="fa fa-check"></i><b>1.4.2</b> Median</a></li>
<li class="chapter" data-level="1.4.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#mode"><i class="fa fa-check"></i><b>1.4.3</b> Mode</a></li>
<li class="chapter" data-level="1.4.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#examples"><i class="fa fa-check"></i><b>1.4.4</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#measures-of-spread"><i class="fa fa-check"></i><b>1.5</b> Measures of Spread</a><ul>
<li class="chapter" data-level="1.5.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#range"><i class="fa fa-check"></i><b>1.5.1</b> Range</a></li>
<li class="chapter" data-level="1.5.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#inter-quartile-range-iqr"><i class="fa fa-check"></i><b>1.5.2</b> Inter-Quartile Range (IQR)</a></li>
<li class="chapter" data-level="1.5.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#variance"><i class="fa fa-check"></i><b>1.5.3</b> Variance</a></li>
<li class="chapter" data-level="1.5.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#standard-deviation"><i class="fa fa-check"></i><b>1.5.4</b> Standard Deviation</a></li>
<li class="chapter" data-level="1.5.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#coefficient-of-variation"><i class="fa fa-check"></i><b>1.5.5</b> Coefficient of Variation</a></li>
<li class="chapter" data-level="1.5.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#empirical-rules"><i class="fa fa-check"></i><b>1.5.6</b> Empirical Rules</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#shape"><i class="fa fa-check"></i><b>1.6</b> Shape</a><ul>
<li class="chapter" data-level="1.6.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#symmetry"><i class="fa fa-check"></i><b>1.6.1</b> Symmetry</a></li>
<li class="chapter" data-level="1.6.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#unimodal-or-multi-modal"><i class="fa fa-check"></i><b>1.6.2</b> Unimodal or Multi-modal</a></li>
<li class="chapter" data-level="1.6.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#skew"><i class="fa fa-check"></i><b>1.6.3</b> Skew</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>1.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-probability.html"><a href="2-probability.html"><i class="fa fa-check"></i><b>2</b> Probability</a><ul>
<li class="chapter" data-level="2.1" data-path="2-probability.html"><a href="2-probability.html#introduction-to-set-theory"><i class="fa fa-check"></i><b>2.1</b> Introduction to Set Theory</a><ul>
<li class="chapter" data-level="2.1.1" data-path="2-probability.html"><a href="2-probability.html#composition-of-events"><i class="fa fa-check"></i><b>2.1.1</b> Composition of events</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2-probability.html"><a href="2-probability.html#probability-rules"><i class="fa fa-check"></i><b>2.2</b> Probability Rules</a><ul>
<li class="chapter" data-level="2.2.1" data-path="2-probability.html"><a href="2-probability.html#simple-rules"><i class="fa fa-check"></i><b>2.2.1</b> Simple Rules</a></li>
<li class="chapter" data-level="2.2.2" data-path="2-probability.html"><a href="2-probability.html#conditional-probability"><i class="fa fa-check"></i><b>2.2.2</b> Conditional Probability</a></li>
<li class="chapter" data-level="2.2.3" data-path="2-probability.html"><a href="2-probability.html#summary-of-probability-rules"><i class="fa fa-check"></i><b>2.2.3</b> Summary of Probability Rules</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-probability.html"><a href="2-probability.html#discrete-random-variables"><i class="fa fa-check"></i><b>2.3</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="2-probability.html"><a href="2-probability.html#introduction-to-discrete-random-variables"><i class="fa fa-check"></i><b>2.3.1</b> Introduction to Discrete Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-probability.html"><a href="2-probability.html#common-discrete-distributions"><i class="fa fa-check"></i><b>2.4</b> Common Discrete Distributions</a><ul>
<li class="chapter" data-level="2.4.1" data-path="2-probability.html"><a href="2-probability.html#binomial-distribution"><i class="fa fa-check"></i><b>2.4.1</b> Binomial Distribution</a></li>
<li class="chapter" data-level="2.4.2" data-path="2-probability.html"><a href="2-probability.html#poisson-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Poisson Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="2-probability.html"><a href="2-probability.html#continuous-random-variables"><i class="fa fa-check"></i><b>2.5</b> Continuous Random Variables</a><ul>
<li class="chapter" data-level="2.5.1" data-path="2-probability.html"><a href="2-probability.html#uniform01-distribution"><i class="fa fa-check"></i><b>2.5.1</b> Uniform(0,1) Distribution</a></li>
<li class="chapter" data-level="2.5.2" data-path="2-probability.html"><a href="2-probability.html#exponential-distribution"><i class="fa fa-check"></i><b>2.5.2</b> Exponential Distribution</a></li>
<li class="chapter" data-level="2.5.3" data-path="2-probability.html"><a href="2-probability.html#normal-distribution"><i class="fa fa-check"></i><b>2.5.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="2.5.4" data-path="2-probability.html"><a href="2-probability.html#standardizing"><i class="fa fa-check"></i><b>2.5.4</b> Standardizing</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="2-probability.html"><a href="2-probability.html#r-quick-reference"><i class="fa fa-check"></i><b>2.6</b> R Quick Reference</a></li>
<li class="chapter" data-level="2.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>2.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html"><i class="fa fa-check"></i><b>3</b> Confidence Intervals via Bootstrapping</a><ul>
<li class="chapter" data-level="3.1" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#theory-of-bootstrapping"><i class="fa fa-check"></i><b>3.1</b> Theory of Bootstrapping</a></li>
<li class="chapter" data-level="3.2" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#conducting-a-bootstrap"><i class="fa fa-check"></i><b>3.2</b> Conducting a Bootstrap</a></li>
<li class="chapter" data-level="3.3" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#quantile-based-confidence-intervals"><i class="fa fa-check"></i><b>3.3</b> Quantile-based Confidence Intervals</a></li>
<li class="chapter" data-level="3.4" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#additional-examples"><i class="fa fa-check"></i><b>3.4</b> Additional Examples</a></li>
<li class="chapter" data-level="3.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html"><i class="fa fa-check"></i><b>4</b> Sampling Distribution of <span class="math inline">\(\bar{X}\)</span></a><ul>
<li class="chapter" data-level="4.1" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#enlightening-example"><i class="fa fa-check"></i><b>4.1</b> Enlightening Example</a></li>
<li class="chapter" data-level="4.2" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#mathematical-details"><i class="fa fa-check"></i><b>4.2</b> Mathematical details</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#probability-rules-for-expectations-and-variances"><i class="fa fa-check"></i><b>4.2.1</b> Probability Rules for Expectations and Variances</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#mean-and-variance-of-the-sample-mean"><i class="fa fa-check"></i><b>4.2.2</b> Mean and Variance of the Sample Mean</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#distribution-of-barx"><i class="fa fa-check"></i><b>4.3</b> Distribution of <span class="math inline">\(\bar{X}\)</span></a></li>
<li class="chapter" data-level="4.4" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#central-limit-theorem"><i class="fa fa-check"></i><b>4.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="4.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html"><i class="fa fa-check"></i><b>5</b> Confidence Intervals for <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="5.1" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html#asymptotic-result-sigma-known"><i class="fa fa-check"></i><b>5.1</b> Asymptotic result (<span class="math inline">\(\sigma\)</span> known)</a></li>
<li class="chapter" data-level="5.2" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html#asymptotoic-result-sigma-unknown"><i class="fa fa-check"></i><b>5.2</b> Asymptotoic result (<span class="math inline">\(\sigma\)</span> unknown)</a></li>
<li class="chapter" data-level="5.3" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html#sample-size-selection"><i class="fa fa-check"></i><b>5.3</b> Sample Size Selection</a></li>
<li class="chapter" data-level="5.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html"><i class="fa fa-check"></i><b>6</b> Hypothesis Tests for the mean of a population</a><ul>
<li class="chapter" data-level="6.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#writing-hypotheses"><i class="fa fa-check"></i><b>6.1</b> Writing Hypotheses</a><ul>
<li class="chapter" data-level="6.1.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>6.1.1</b> Null and alternative hypotheses</a></li>
<li class="chapter" data-level="6.1.2" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#error"><i class="fa fa-check"></i><b>6.1.2</b> Error</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#conducting-a-hypothesis-test-for-mu"><i class="fa fa-check"></i><b>6.2</b> Conducting a Hypothesis Test for <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#why-should-hypotheses-use-mu-and-not-barx"><i class="fa fa-check"></i><b>6.2.1</b> Why should hypotheses use <span class="math inline">\(\mu\)</span> and not <span class="math inline">\(\bar{x}\)</span>?</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#a-note-on-calculating-p-values"><i class="fa fa-check"></i><b>6.2.2</b> A note on calculating p-values</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#additional-examples"><i class="fa fa-check"></i><b>6.3</b> Additional Examples</a></li>
<li class="chapter" data-level="6.4" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#p-values-vs-cutoff-values"><i class="fa fa-check"></i><b>6.4</b> P-values vs cutoff values</a></li>
<li class="chapter" data-level="6.5" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#running-a-t-test-in-r"><i class="fa fa-check"></i><b>6.5</b> Running a t-test in R</a></li>
<li class="chapter" data-level="6.6" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>6.6</b> Type I and Type II Errors</a><ul>
<li class="chapter" data-level="6.6.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#power-and-sample-size-selection"><i class="fa fa-check"></i><b>6.6.1</b> Power and Sample Size Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>6.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> Two-Sample Hypothesis Tests and Confidence Intervals</a><ul>
<li class="chapter" data-level="7.1" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#difference-in-means-between-two-groups"><i class="fa fa-check"></i><b>7.1</b> Difference in means between two groups</a><ul>
<li class="chapter" data-level="7.1.1" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#inference-via-resampling"><i class="fa fa-check"></i><b>7.1.1</b> Inference via resampling</a></li>
<li class="chapter" data-level="7.1.2" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#inference-via-asymptotic-results-unequal-variance-assumption"><i class="fa fa-check"></i><b>7.1.2</b> Inference via asymptotic results (unequal variance assumption)</a></li>
<li class="chapter" data-level="7.1.3" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#inference-via-asymptotic-results-equal-variance-assumption"><i class="fa fa-check"></i><b>7.1.3</b> Inference via asymptotic results (equal variance assumption)</a></li>
<li class="chapter" data-level="7.1.4" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#additional-example"><i class="fa fa-check"></i><b>7.1.4</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#difference-in-means-between-two-groups-paired-data"><i class="fa fa-check"></i><b>7.2</b> Difference in means between two groups: Paired Data</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#additional-example-1"><i class="fa fa-check"></i><b>7.2.1</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html"><i class="fa fa-check"></i><b>8</b> Testing Model Assumptions</a><ul>
<li class="chapter" data-level="8.1" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#testing-normality"><i class="fa fa-check"></i><b>8.1</b> Testing Normality</a><ul>
<li class="chapter" data-level="8.1.1" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#visual-inspection---qqplots"><i class="fa fa-check"></i><b>8.1.1</b> Visual Inspection - QQplots</a></li>
<li class="chapter" data-level="8.1.2" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#tests-for-normality"><i class="fa fa-check"></i><b>8.1.2</b> Tests for Normality</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#testing-equal-variance"><i class="fa fa-check"></i><b>8.2</b> Testing Equal Variance</a><ul>
<li class="chapter" data-level="8.2.1" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#visual-inspection"><i class="fa fa-check"></i><b>8.2.1</b> Visual Inspection</a></li>
<li class="chapter" data-level="8.2.2" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#tests-for-equal-variance"><i class="fa fa-check"></i><b>8.2.2</b> Tests for Equal Variance</a></li>
<li class="chapter" data-level="8.2.3" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#symmetry-of-the-f-distribution"><i class="fa fa-check"></i><b>8.2.3</b> Symmetry of the F-distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#power-of-the-f-test"><i class="fa fa-check"></i><b>8.3</b> Power of the F-test</a></li>
<li class="chapter" data-level="8.4" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#theoretical-distribution-vs-bootstrap"><i class="fa fa-check"></i><b>8.4</b> Theoretical distribution vs bootstrap</a></li>
<li class="chapter" data-level="8.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html"><i class="fa fa-check"></i><b>9</b> Analysis of Variance (ANOVA)</a><ul>
<li class="chapter" data-level="9.1" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#model"><i class="fa fa-check"></i><b>9.1</b> Model</a></li>
<li class="chapter" data-level="9.2" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#theory"><i class="fa fa-check"></i><b>9.2</b> Theory</a><ul>
<li class="chapter" data-level="9.2.1" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#anova-table"><i class="fa fa-check"></i><b>9.2.1</b> Anova Table</a></li>
<li class="chapter" data-level="9.2.2" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#anova-using-simple-vs-complex-models."><i class="fa fa-check"></i><b>9.2.2</b> ANOVA using Simple vs Complex models.</a></li>
<li class="chapter" data-level="9.2.3" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#parameter-estimates-and-confidence-intervals"><i class="fa fa-check"></i><b>9.2.3</b> Parameter Estimates and Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#anova-in-r"><i class="fa fa-check"></i><b>9.3</b> Anova in R</a></li>
<li class="chapter" data-level="9.4" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#multiple-comparisons"><i class="fa fa-check"></i><b>9.4</b> Multiple comparisons</a></li>
<li class="chapter" data-level="9.5" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#different-model-representations"><i class="fa fa-check"></i><b>9.5</b> Different Model Representations</a><ul>
<li class="chapter" data-level="9.5.1" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#theory-1"><i class="fa fa-check"></i><b>9.5.1</b> Theory</a></li>
<li class="chapter" data-level="9.5.2" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#model-representations-in-r"><i class="fa fa-check"></i><b>9.5.2</b> Model Representations in R</a></li>
<li class="chapter" data-level="9.5.3" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#implications-on-the-anova-table"><i class="fa fa-check"></i><b>9.5.3</b> Implications on the ANOVA table</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>9.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="10-regression.html"><a href="10-regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a><ul>
<li class="chapter" data-level="10.1" data-path="10-regression.html"><a href="10-regression.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>10.1</b> Pearson’s Correlation Coefficient</a></li>
<li class="chapter" data-level="10.2" data-path="10-regression.html"><a href="10-regression.html#model-theory"><i class="fa fa-check"></i><b>10.2</b> Model Theory</a><ul>
<li class="chapter" data-level="10.2.1" data-path="10-regression.html"><a href="10-regression.html#anova-interpretation"><i class="fa fa-check"></i><b>10.2.1</b> Anova Interpretation</a></li>
<li class="chapter" data-level="10.2.2" data-path="10-regression.html"><a href="10-regression.html#confidence-intervals-vs-prediction-intervals"><i class="fa fa-check"></i><b>10.2.2</b> Confidence Intervals vs Prediction Intervals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="10-regression.html"><a href="10-regression.html#extrapolation"><i class="fa fa-check"></i><b>10.3</b> Extrapolation</a></li>
<li class="chapter" data-level="10.4" data-path="10-regression.html"><a href="10-regression.html#checking-model-assumptions"><i class="fa fa-check"></i><b>10.4</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="10.5" data-path="10-regression.html"><a href="10-regression.html#common-problems"><i class="fa fa-check"></i><b>10.5</b> Common Problems</a><ul>
<li class="chapter" data-level="10.5.1" data-path="10-regression.html"><a href="10-regression.html#influential-points"><i class="fa fa-check"></i><b>10.5.1</b> Influential Points</a></li>
<li class="chapter" data-level="10.5.2" data-path="10-regression.html"><a href="10-regression.html#transformations"><i class="fa fa-check"></i><b>10.5.2</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html"><i class="fa fa-check"></i><b>11</b> Contingency Tables</a><ul>
<li class="chapter" data-level="11.1" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html#expected-counts"><i class="fa fa-check"></i><b>11.1</b> Expected Counts</a></li>
<li class="chapter" data-level="11.2" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html#hypothesis-testing"><i class="fa fa-check"></i><b>11.2</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="11.3" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html#rxc-tables"><i class="fa fa-check"></i><b>11.3</b> RxC tables</a></li>
<li class="chapter" data-level="11.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>11.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html"><i class="fa fa-check"></i>Appendix A : Resampling Linear Models</a><ul>
<li class="chapter" data-level="11.5" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#using-lm-for-many-analyses"><i class="fa fa-check"></i><b>11.5</b> Using <code>lm()</code> for many analyses</a><ul>
<li class="chapter" data-level="11.5.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#one-sample-t-tests"><i class="fa fa-check"></i><b>11.5.1</b> One-sample t-tests</a></li>
<li class="chapter" data-level="11.5.2" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#two-sample-t-tests"><i class="fa fa-check"></i><b>11.5.2</b> Two-sample t-tests</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#creating-simulated-data"><i class="fa fa-check"></i><b>11.6</b> Creating Simulated Data</a><ul>
<li class="chapter" data-level="11.6.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#observational-studies-vs-designed-experiments"><i class="fa fa-check"></i><b>11.6.1</b> Observational Studies vs Designed Experiments</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#confidence-interval-types"><i class="fa fa-check"></i><b>11.7</b> Confidence Interval Types</a><ul>
<li class="chapter" data-level="11.7.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#normal-intervals"><i class="fa fa-check"></i><b>11.7.1</b> Normal intervals</a></li>
<li class="chapter" data-level="11.7.2" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#percentile-intervals"><i class="fa fa-check"></i><b>11.7.2</b> Percentile intervals</a></li>
<li class="chapter" data-level="11.7.3" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#basic-intervals"><i class="fa fa-check"></i><b>11.7.3</b> Basic intervals</a></li>
<li class="chapter" data-level="11.7.4" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#towards-bias-corrected-and-accelerated-intervals-bca"><i class="fa fa-check"></i><b>11.7.4</b> Towards bias-corrected and accelerated intervals (BCa)</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#bootstrap-confidence-intervals-in-r"><i class="fa fa-check"></i><b>11.8</b> Bootstrap Confidence Intervals in R</a><ul>
<li class="chapter" data-level="11.8.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#using-carboot-function"><i class="fa fa-check"></i><b>11.8.1</b> Using <code>car::Boot()</code> function</a></li>
<li class="chapter" data-level="11.8.2" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#using-the-boot-package"><i class="fa fa-check"></i><b>11.8.2</b> Using the <code>boot</code> package</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>11.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-b-alternative-bootstrap-code.html"><a href="appendix-b-alternative-bootstrap-code.html"><i class="fa fa-check"></i>Appendix B : Alternative Bootstrap Code</a><ul>
<li class="chapter" data-level="" data-path="appendix-b-alternative-bootstrap-code.html"><a href="appendix-b-alternative-bootstrap-code.html#mosaic-package"><i class="fa fa-check"></i>Mosaic Package</a></li>
<li class="chapter" data-level="" data-path="appendix-b-alternative-bootstrap-code.html"><a href="appendix-b-alternative-bootstrap-code.html#base-r-code"><i class="fa fa-check"></i>Base R Code</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Methodology, Second Edition</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="confidence-intervals-via-bootstrapping" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Confidence Intervals via Bootstrapping</h1>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb73-1"></a><span class="kw">library</span>(ggplot2)    <span class="co"># graphing functions</span></span>
<span id="cb73-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb73-2"></a><span class="kw">library</span>(dplyr)      <span class="co"># data summary tools</span></span>
<span id="cb73-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb73-3"></a><span class="kw">library</span>(boot)       <span class="co"># bootstrap</span></span>
<span id="cb73-4"><a href="3-confidence-intervals-via-bootstrapping.html#cb73-4"></a></span>
<span id="cb73-5"><a href="3-confidence-intervals-via-bootstrapping.html#cb73-5"></a><span class="co"># Set default behavior of ggplot2 graphs to be black/white theme</span></span>
<span id="cb73-6"><a href="3-confidence-intervals-via-bootstrapping.html#cb73-6"></a><span class="kw">theme_set</span>(<span class="kw">theme_bw</span>())</span></code></pre></div>
<div id="theory-of-bootstrapping" class="section level2">
<h2><span class="header-section-number">3.1</span> Theory of Bootstrapping</h2>
<p>Suppose that we had a population of interest and we wish to estimate the mean of that population (the population mean we’ll denote as <span class="math inline">\(\mu\)</span>). We can’t observe every member of the population (which would be prohibitively expensive) so instead we take a random sample and from that sample calculate a sample mean (which we’ll denote <span class="math inline">\(\bar{x}\)</span>). We believe that <span class="math inline">\(\bar{x}\)</span> will be a good estimator of <span class="math inline">\(\mu\)</span>, but it will vary from sample to sample and won’t be exactly equal to <span class="math inline">\(\mu\)</span>.</p>
<p>Next suppose we wish to ask if a particular value for <span class="math inline">\(\mu\)</span>, say <span class="math inline">\(\mu_{0}\)</span>, is consistent with our observed data? We know that <span class="math inline">\(\bar{x}\)</span> will vary from sample to sample, but we have no idea how much it will vary between samples. However, if we could understand how much <span class="math inline">\(\bar{x}\)</span> varied sample to sample, we could answer the question. For example, suppose that <span class="math inline">\(\bar{x}=5\)</span> and we know that <span class="math inline">\(\bar{x}\)</span> varied about <span class="math inline">\(\pm2\)</span> from sample to sample. Then I’d say that possible values of <span class="math inline">\(\mu_{0}\)</span> in the interval <span class="math inline">\(3\)</span> to <span class="math inline">\(7\)</span> <span class="math inline">\(\left(5\pm2\right)\)</span> are reasonable values for <span class="math inline">\(\mu\)</span> and anything outside that interval is not reasonable.</p>
<p>Therefore, if we could take many, many repeated samples from the population and calculate our test statistic <span class="math inline">\(\bar{x}\)</span> for each sample, we could rule out possible values of <span class="math inline">\(\mu\)</span>. Unfortunately we don’t have the time or money to repeatedly sample from the actual population, but we could sample from our best approximation to what the population is like.</p>
<p>Suppose we were to sample from a population of shapes, and we observed <span class="math inline">\(4/9\)</span> of the sample were squares, <span class="math inline">\(3/9\)</span> were circles, and a triangle and a diamond. Then our best guess of what the population that we sampled from was a population with <span class="math inline">\(4/9\)</span> squares, <span class="math inline">\(3/9\)</span> circles, and <span class="math inline">\(1/9\)</span> of triangles and diamonds.</p>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Using this approximated population (which is just many many copies of our sample data), we can repeatedly sample <span class="math inline">\(\bar{x}^{*}\)</span> values to create an estimate of the sampling distribution of <span class="math inline">\(\bar{x}\)</span>.</p>
<p>Because our approximate population is just an infinite number of copies of our sample data, then sampling from the approximate population is equivalent to sampling with replacement from our sample data. If I take <span class="math inline">\(n\)</span> samples from <span class="math inline">\(n\)</span> distinct objects with replacement, then the process can be thought of as mixing the <span class="math inline">\(n\)</span> objects in a bowl and taking an object at random, noting which it is, replace it into the bowl, and then draw the next sample. Practically, this means some objects will be selected more than once and some will not be chosen at all. To sample our observed data with replacement, we can use the <code>sample()</code> function in R.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb74-1"></a>names=<span class="kw">c</span>(<span class="st">&#39;Alison&#39;</span>,<span class="st">&#39;Brandon&#39;</span>,<span class="st">&#39;Casey&#39;</span>,<span class="st">&#39;Derek&#39;</span>,<span class="st">&#39;Elise&#39;</span>)</span>
<span id="cb74-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb74-2"></a><span class="kw">sample</span>(names, <span class="kw">length</span>(names), <span class="dt">replace=</span>T)</span></code></pre></div>
<pre><code>## [1] &quot;Elise&quot;  &quot;Alison&quot; &quot;Elise&quot;  &quot;Alison&quot; &quot;Derek&quot;</code></pre>
<p>Notice Alison has selected twice, while Brandon has not been selected at all.</p>
<p>The sampling from the estimated population via sampling from the observed data is called <strong>bootstrapping</strong> because we are making no distributional assumptions about where the data came from, and the idiom “Pulling yourself up by your bootstraps” seemed appropriate.</p>
<p><strong>Example:</strong> Mercury Levels in Fish from Florida Lakes</p>
<p>A data set provided by the Lock<span class="math inline">\(^{5}\)</span> introductory statistics textbook looks at the mercury levels in fish harvested from lakes in Florida. There are approximately 7,700 lakes in Florida that are larger than 10 acres. As part of a study to assess the average mercury contamination in these lakes, a random sample of <span class="math inline">\(n=53\)</span> lakes, an unspecified number of fish were harvested and the average mercury level (in ppm) was calculated for fish in each lake. The goal of the study was to assess if the average mercury concentration was greater than the 1969 EPA “legally actionable level” of 0.5 ppm.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb76-1"></a><span class="co"># read the Lakes data set</span></span>
<span id="cb76-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb76-2"></a>Lakes &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;http://www.lock5stat.com/datasets/FloridaLakes.csv&#39;</span>)</span>
<span id="cb76-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb76-3"></a><span class="co"># make a nice picture... dot plots are very similar to histograms</span></span>
<span id="cb76-4"><a href="3-confidence-intervals-via-bootstrapping.html#cb76-4"></a><span class="co"># dot plots can be informative for small samples</span></span>
<span id="cb76-5"><a href="3-confidence-intervals-via-bootstrapping.html#cb76-5"></a><span class="kw">ggplot</span>(Lakes, <span class="kw">aes</span>(<span class="dt">x=</span>AvgMercury)) <span class="op">+</span></span>
<span id="cb76-6"><a href="3-confidence-intervals-via-bootstrapping.html#cb76-6"></a><span class="st">  </span><span class="kw">geom_dotplot</span>()</span></code></pre></div>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>We can calculate mean average mercury level for the <span class="math inline">\(n=53\)</span> lakes</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb77-1"></a>Lakes <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">xbar =</span> <span class="kw">mean</span>( AvgMercury ))</span></code></pre></div>
<pre><code>##        xbar
## 1 0.5271698</code></pre>
<p>The sample mean is greater than <span class="math inline">\(0.5\)</span> but not by too much. Is a true population mean concentration <span class="math inline">\(\mu_{Hg}\)</span> that is <span class="math inline">\(0.5\)</span> or less incompatible with our observed data? Is our data sufficient evidence to conclude that the average mercury content is greater than <span class="math inline">\(0.5\)</span>? Perhaps the true average mercury content is less than (or equal to) <span class="math inline">\(0.5\)</span> and we just happened to get a random sample that with a mean greater than <span class="math inline">\(0.5\)</span>?</p>
</div>
<div id="conducting-a-bootstrap" class="section level2">
<h2><span class="header-section-number">3.2</span> Conducting a Bootstrap</h2>
<p>The first step in answering these questions is to create an estimate of the sampling distribution of <span class="math inline">\(\bar{x}_{Hg}\)</span>. To do this, we will sample from the approximate population of lakes, which is just many many replicated copies of our sample data. There are many ways to bootstrap using R, and chosen here is to introduce the package <code>boot</code> for conducting the bootstrap for us with minimal code. For alternative methods using base R or the package <code>mosaic</code>, see Appendix A.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb79-1"></a><span class="kw">library</span>(boot)</span></code></pre></div>
<p>To use the <code>boot()</code> function within the <code>boot</code> package, we will have to define a function for the resampling to occur. Below, we create the function <code>mean.function</code>, that accepts a vector (our observations) and calculates the mean. The index is so that <code>boot()</code> can do the resampling. How do you think we could change this to bootstrap different statistics?</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb80-1"></a>mean.function &lt;-<span class="st"> </span><span class="cf">function</span>(x, index) {</span>
<span id="cb80-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb80-2"></a>  d &lt;-<span class="st"> </span>x[index]</span>
<span id="cb80-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb80-3"></a>  <span class="kw">return</span>(<span class="kw">mean</span>(d))  }</span></code></pre></div>
<p>Once you have defined what you would like to bootstrap, the function <code>boot()</code> is a simple call in R, and produces the number of iterations <span class="math inline">\(R\)</span> we choose. Let us try running <span class="math inline">\(R = 10000\)</span> bootstrap iterations.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb81-1"></a><span class="co"># create the Estimated Sampling Distribution of xbar</span></span>
<span id="cb81-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb81-2"></a>BootDist &lt;-<span class="st"> </span><span class="kw">boot</span>(<span class="dt">data =</span> Lakes<span class="op">$</span>AvgMercury, <span class="dt">statistic =</span> mean.function, <span class="dt">R=</span><span class="dv">10000</span>)</span></code></pre></div>
<p>There are many outputs available within the output of <code>boot()</code>. We are interested in the calculated statistic for each redraw, which is saved within the output as the variable <span class="math inline">\(t\)</span>. We can place the calculated means for each redraw into a data frame and produce a visualization of the estimated sampling distribution of <span class="math inline">\(\bar{x}\)</span>.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb82-1"></a><span class="co"># The first few calculated means.</span></span>
<span id="cb82-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb82-2"></a><span class="kw">head</span>(BootDist<span class="op">$</span>t)</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 0.5209434
## [2,] 0.4884906
## [3,] 0.5766038
## [4,] 0.5275472
## [5,] 0.5830189
## [6,] 0.5245283</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb84-1"></a><span class="co"># show a histogram of the estimated sampling distribution of xbar</span></span>
<span id="cb84-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb84-2"></a>BootDist.graph &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">xbar=</span>BootDist<span class="op">$</span>t)</span>
<span id="cb84-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb84-3"></a><span class="kw">ggplot</span>(BootDist.graph, <span class="kw">aes</span>(<span class="dt">x=</span>xbar)) <span class="op">+</span></span>
<span id="cb84-4"><a href="3-confidence-intervals-via-bootstrapping.html#cb84-4"></a><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb84-5"><a href="3-confidence-intervals-via-bootstrapping.html#cb84-5"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Estimated Sampling distribution of xbar&#39;</span> )</span></code></pre></div>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="quantile-based-confidence-intervals" class="section level2">
<h2><span class="header-section-number">3.3</span> Quantile-based Confidence Intervals</h2>
<p>In many cases we have seen, the sampling distribution of a statistic is centered on the parameter we are interested in estimating and is symmetric about that parameter. There are actually several ways to create a confidence interval from the estimated sampling distribution. The method presented here is called the “percentile” method and works when the sampling distribution is symmetric and the estimator we are using is unbiased. For example, we expect that the sample mean <span class="math inline">\(\bar{x}\)</span> should be a good estimate of the population mean <span class="math inline">\(\mu\)</span> and the sampling distribution of <span class="math inline">\(\bar{x}\)</span> should look something like the following.</p>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>There are two points, (call them <span class="math inline">\(L\)</span> and <span class="math inline">\(U\)</span>) where for our given sample size and population we are sampling from, where we expect that <span class="math inline">\(95\%\)</span> of the sample means to fall within. That is to say, <span class="math inline">\(L\)</span> and <span class="math inline">\(U\)</span> capture the middle <span class="math inline">\(95\%\)</span> of the sampling distribution of <span class="math inline">\(\bar{x}\)</span>.</p>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>These sample means are randomly distributed about the population mean <span class="math inline">\(\mu\)</span>. Given our sample data and sample mean <span class="math inline">\(\bar{x}\)</span>, we can examine how our simulated values of <span class="math inline">\(\bar{x}^{*}\)</span> vary about <span class="math inline">\(\bar{x}\)</span>. I expect that these simulated sample means <span class="math inline">\(\bar{x}^{*}\)</span> should vary about <span class="math inline">\(\bar{x}\)</span> in the same way that <span class="math inline">\(\bar{x}\)</span> values vary around <span class="math inline">\(\mu\)</span>. Below are three estimated sampling distributions that we might obtain from three different samples and their associated sample means.</p>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>For each possible sample, we could consider creating the estimated sampling distribution of <span class="math inline">\(\bar{X}\)</span> and calculating the <span class="math inline">\(L\)</span> and <span class="math inline">\(U\)</span> values that capture the middle <span class="math inline">\(95\%\)</span> of the estimated sampling distribution. Below are twenty samples, where we’ve calculated this interval for each sample.</p>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Most of these intervals contain the true parameter <span class="math inline">\(\mu\)</span>, that we are trying to estimate. In practice, I will only take one sample and therefore will only calculate one sample mean and one interval, but I want to recognize that the method I used to produce the interval (i.e. take a random sample, calculate the mean and then the interval) will result in intervals where only <span class="math inline">\(95\%\)</span> of those intervals will contain the mean <span class="math inline">\(\mu\)</span>. Therefore, I will refer to the interval as a <span class="math inline">\(95\%\)</span> confidence interval.</p>
<p>After the sample is taken and the interval is calculated, the numbers lower and upper bounds of the confidence interval are fixed. Because <span class="math inline">\(\mu\)</span> is a constant value and the confidence interval is fixed, nothing is changing. To distinguish between a future random event and the fixed (but unknown) outcome of if I ended up with an interval that contains <span class="math inline">\(\mu\)</span> and we use the term confidence interval instead of probability interval.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb85-1"></a><span class="co"># calculate the 95% confidence interval using middle 95% of xbars</span></span>
<span id="cb85-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb85-2"></a><span class="kw">quantile</span>( BootDist<span class="op">$</span>t, <span class="dt">probs=</span><span class="kw">c</span>(.<span class="dv">025</span>, <span class="fl">.975</span>) )</span></code></pre></div>
<pre><code>##      2.5%     97.5% 
## 0.4364104 0.6184953</code></pre>
<p>There are several ways to interpret this interval.</p>
<ol style="list-style-type: decimal">
<li><p>The process used to calculate this interval (take a random sample, calculate a statistic, repeatedly re-sample, and take the middle <span class="math inline">\(95\%\)</span>) is a process that results in an interval that contains the parameter of interest on <span class="math inline">\(95\%\)</span> of the samples we could have collected, however we don’t know if the particular sample we collected and its resulting interval of <span class="math inline">\(\left(0.44,\,0.62\right)\)</span> is one of the intervals containing <span class="math inline">\(\mu\)</span>.</p></li>
<li><p>We are <span class="math inline">\(95\%\)</span> confident that <span class="math inline">\(\mu\)</span> is in the interval <span class="math inline">\(\left(0.44,\,0.62\right)\)</span>. This is delightfully vague and should be interpreted as a shorter version of the previous interpretation.</p></li>
<li><p>The interval <span class="math inline">\(\left(0.44,\,0.62\right)\)</span> is the set of values of <span class="math inline">\(\mu\)</span> that are consistent with the observed data at the <span class="math inline">\(0.05\)</span> threshold of statistical significance for a two-sided hypothesis test</p></li>
</ol>
</div>
<div id="additional-examples" class="section level2">
<h2><span class="header-section-number">3.4</span> Additional Examples</h2>
<p><strong>Example:</strong> Fuel Economy</p>
<p>Suppose we have data regarding fuel economy of <span class="math inline">\(5\)</span> new vehicles of the same make and model and we wish to test if the observed fuel economy is consistent with the advertised <span class="math inline">\(31\)</span> mpg at highway speeds. Here are the data:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb87-1"></a>CarMPG &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">ID=</span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="dt">mpg =</span> <span class="kw">c</span>(<span class="fl">31.8</span>, <span class="fl">32.1</span>, <span class="fl">32.5</span>, <span class="fl">30.9</span>, <span class="fl">31.3</span>) )</span>
<span id="cb87-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb87-2"></a>CarMPG <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">xbar=</span><span class="kw">mean</span>(mpg) )</span></code></pre></div>
<pre><code>##    xbar
## 1 31.72</code></pre>
<p>We will use the sample mean to assess if the sample fuel efficiency is consistent with the advertised number. Because these cars could be considered a random sample of all new cars of this make, we will create the estimated sampling distribution using the bootstrap re-sampling of the data.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-1"></a><span class="co"># Run the bootstrap now with CarMPG$mpg as our data</span></span>
<span id="cb89-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-2"></a>BootDist &lt;-<span class="st"> </span><span class="kw">boot</span>(<span class="dt">data =</span> CarMPG<span class="op">$</span>mpg, <span class="dt">statistic =</span> mean.function, <span class="dt">R=</span><span class="dv">10000</span>)</span>
<span id="cb89-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-3"></a></span>
<span id="cb89-4"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-4"></a><span class="co"># show a histogram of the sampling distribution of xbar</span></span>
<span id="cb89-5"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-5"></a>BootDist.graph &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">xbar=</span>BootDist<span class="op">$</span>t)</span>
<span id="cb89-6"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-6"></a><span class="kw">ggplot</span>(BootDist.graph, <span class="kw">aes</span>(<span class="dt">x=</span>xbar)) <span class="op">+</span></span>
<span id="cb89-7"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-7"></a><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></span>
<span id="cb89-8"><a href="3-confidence-intervals-via-bootstrapping.html#cb89-8"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Sampling Distribution of mean(mpg)&#39;</span>)</span></code></pre></div>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb90-1"></a><span class="co"># calculate the 95% confidence interval using middle 95% of xbars</span></span>
<span id="cb90-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb90-2"></a><span class="kw">quantile</span>( BootDist<span class="op">$</span>t, <span class="dt">probs=</span><span class="kw">c</span>(.<span class="dv">025</span>, <span class="fl">.975</span>) )</span></code></pre></div>
<pre><code>##  2.5% 97.5% 
## 31.22 32.20</code></pre>
<p>We see that the <span class="math inline">\(95\%\)</span> confidence interval is <span class="math inline">\(\left(31.2,\,32.2\right)\)</span> and does not actually contain the advertised <span class="math inline">\(31\)</span> mpg. However, I don’t think we would object to a car manufacturer selling us a car that is better than advertised.</p>
<p><strong>Example:</strong> Pulse Rate of College Students</p>
<p>In the package Lock5Data, the dataset <code>GPAGender</code> contains information taken from undergraduate students in an Introductory Statistics course. This is a convenience sample, but could be considered representative of students at that university. One of the covariates measured was the students pulse rate and we will use this to create a confidence interval for average pulse of students at that university.</p>
<p>First we’ll look at the raw data.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb92-1"></a><span class="kw">data</span>(GPAGender, <span class="dt">package=</span><span class="st">&#39;Lock5Data&#39;</span>)     <span class="co"># load the dataset</span></span>
<span id="cb92-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb92-2"></a><span class="co"># Now a nice histogram</span></span>
<span id="cb92-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb92-3"></a><span class="kw">ggplot</span>(GPAGender, <span class="kw">aes</span>(<span class="dt">x=</span>Pulse, <span class="dt">y=</span>..density..)) <span class="op">+</span></span>
<span id="cb92-4"><a href="3-confidence-intervals-via-bootstrapping.html#cb92-4"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb92-5"><a href="3-confidence-intervals-via-bootstrapping.html#cb92-5"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Sample Data&#39;</span>)</span></code></pre></div>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>It is worth noting this was supposed to be measuring resting heart rates, but there are two students had extremely high pulse rates and six with extremely low rates. The two high values are approximately what you’d expect from someone currently engaged in moderate exercise and the low values are levels we’d expect from highly trained endurance athletes.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb93-1"></a><span class="co"># Summary Statistics</span></span>
<span id="cb93-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb93-2"></a>GPAGender <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">xbar =</span> <span class="kw">mean</span>(Pulse),</span>
<span id="cb93-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb93-3"></a>                        <span class="dt">StdDev =</span> <span class="kw">sd</span>(Pulse))</span></code></pre></div>
<pre><code>##       xbar   StdDev
## 1 69.90379 12.08569</code></pre>
<p>So the sample mean is <span class="math inline">\(\bar{x}=69.9\)</span> but how much should we expect our sample mean to vary from sample to sample when our sample size is <span class="math inline">\(n=343\)</span> people? We’ll estimate the sampling distribution of <span class="math inline">\(\bar{X}\)</span> using the bootstrap.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-1"></a><span class="co"># Create the bootstrap replicates</span></span>
<span id="cb95-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-2"></a>BootDist &lt;-<span class="st"> </span><span class="kw">boot</span>(<span class="dt">data =</span> GPAGender<span class="op">$</span>Pulse, <span class="dt">statistic =</span> mean.function, <span class="dt">R=</span><span class="dv">10000</span>)</span>
<span id="cb95-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-3"></a></span>
<span id="cb95-4"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-4"></a><span class="co"># show a histogram of the sampling distribution of xbar</span></span>
<span id="cb95-5"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-5"></a>BootDist.graph &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">xbar=</span>BootDist<span class="op">$</span>t)</span>
<span id="cb95-6"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-6"></a><span class="kw">ggplot</span>(BootDist.graph, <span class="kw">aes</span>(<span class="dt">x=</span>xbar)) <span class="op">+</span></span>
<span id="cb95-7"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-7"></a><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></span>
<span id="cb95-8"><a href="3-confidence-intervals-via-bootstrapping.html#cb95-8"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Sampling Distribution of mean(Pulse)&#39;</span>)</span></code></pre></div>
<p><img src="03_Bootstrapping_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb96-1"></a><span class="kw">quantile</span>( BootDist<span class="op">$</span>t, <span class="dt">probs=</span><span class="kw">c</span>(.<span class="dv">025</span>, <span class="fl">.975</span>) )</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 68.63265 71.18375</code></pre>
<p>Based on the quantile approach, the <span class="math inline">\(95\%\)</span> bootstrap confidence for the mean pulse rate of undergraduates in the introductory statistics course is <span class="math inline">\(68.7\)</span> to <span class="math inline">\(71.2\)</span> beats per minutes.</p>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">3.5</span> Exercises</h2>
<p>For several of these exercises, we will use data sets from the R package <code>Lock5Data</code>, which greatly contributed to the pedagogical approach of these notes. Install the package from CRAN using the RStudio point-and-click interface <code>Tools -&gt; Install Packages</code>….</p>
<ol style="list-style-type: decimal">
<li>Load the dataset <code>BodyTemp50</code> from the Lock5Data package. This is a dataset of 50 healthy adults. One of the columns of this dataset is the Pulse of the 50 data points, which is the number of heartbeats per minute.
<ol style="list-style-type: lower-alpha">
<li>Create a histogram of the observed pulse values. Comment on the graph and aspects of the graph that might be of scientific interest. Below will help you load the data, and we want to use the <code>Pulse</code> variable.</li>
</ol>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb98-1"></a><span class="kw">data</span>( BodyTemp50, <span class="dt">package=</span><span class="st">&#39;Lock5Data&#39;</span> )</span>
<span id="cb98-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb98-2"></a><span class="co">#?BodyTemp50</span></span></code></pre></div>
<ol start="2" style="list-style-type: lower-alpha">
<li>Calculate the sample mean <span class="math inline">\(\bar{x}\)</span> and sample standard deviation <span class="math inline">\(s\)</span> of the pulses.</li>
<li>Create a dataset of 10000 bootstrap replicates of <span class="math inline">\(\bar{x}^{*}\)</span>.</li>
<li>Create a histogram of the bootstrap replicates. Calculate the mean and standard deviation of this distribution. Notice that the standard deviation of the distribution is often called the Standard Error of <span class="math inline">\(\bar{x}\)</span> and we’ll denote it as <span class="math inline">\(\hat{\sigma}_{\bar{x}}\)</span>.</li>
<li>Using the bootstrap replicates, create a 95% confidence interval for <span class="math inline">\(\mu\)</span>, the average adult heart rate.</li>
<li>Calculate the interval
<span class="math display">\[\left(\bar{x}-2\cdot\hat{\sigma}_{\bar{x}}\,,\,\;\;\bar{x}+2\cdot\hat{\sigma}_{\bar{x}}\right)\]</span>
and comment on its similarity to the interval you calculated in part (e).</li>
</ol></li>
<li>Load the dataset <code>EmployedACS</code> from the <code>Lock5Data</code> package. This is a dataset drawn from American Community Survey results which is conducted monthly by the US Census Bureau and should be representative of US workers. The column <code>HoursWk</code> represents the number of hours worked per week.
<ol style="list-style-type: lower-alpha">
<li>Create a histogram of the observed hours worked. Comment on the graph and aspects of the graph that might be of scientific interest.</li>
<li>Calculate the sample mean <span class="math inline">\(\bar{x}\)</span> and sample standard deviation <span class="math inline">\(s\)</span> of the worked hours per week.</li>
<li>Create a dataset of 10000 bootstrap replicates of <span class="math inline">\(\bar{x}^{*}\)</span>.</li>
<li>Create a histogram of the bootstrap replicates. Calculate the mean and standard deviation of this distribution. Notice that the standard deviation of the distribution is often called the Standard Error of <span class="math inline">\(\bar{x}\)</span> and we’ll denote it as <span class="math inline">\(\sigma_{\bar{x}}\)</span>.</li>
<li>Using the bootstrap replicates, create a 95% confidence interval for <span class="math inline">\(\mu\)</span>, the average worked hours per week.</li>
<li>Calculate the interval
<span class="math display">\[\left(\bar{x}-2\cdot\hat{\sigma}_{\bar{x}}\,,\,\;\;\bar{x}+2\cdot\hat{\sigma}_{\bar{x}}\right)\]</span>
and comment on its similarity to the interval you calculated in part (e).</li>
</ol></li>
<li>Return to the <code>BodyTemp50</code> data within the <code>Lock5Data</code> package, as in Exercise 1.</li>
</ol>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="3-confidence-intervals-via-bootstrapping.html#cb99-1"></a>new.function &lt;-<span class="st"> </span><span class="cf">function</span>(x, index) {</span>
<span id="cb99-2"><a href="3-confidence-intervals-via-bootstrapping.html#cb99-2"></a>  d &lt;-<span class="st"> </span>x[index]</span>
<span id="cb99-3"><a href="3-confidence-intervals-via-bootstrapping.html#cb99-3"></a>  <span class="kw">return</span>(<span class="kw">mean</span>(d))  }  <span class="co">## Hint: sd() calculates the standard deviation</span></span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li>The code above was given in the chapter for calculate the mean of a vector. Modify the code below such that we can prepare a boostrap confidence interval of the <strong>standard deviation</strong>, <span class="math inline">\(\sigma\)</span>.</li>
<li>Create a dataset of 10000 bootstrap replicates of <span class="math inline">\(\sigma^*\)</span>.</li>
<li>Using the bootstrap replicates, create a 95% confidence interval for <span class="math inline">\(\sigma\)</span>, the standard deviation of adult heart rate.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="2-probability.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="4-sampling-distribution-of-barx.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"],
"google": false,
"instapper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dereksonderegger/570/raw/master/03_Bootstrapping.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": [["Statistical-Methods-I.pdf", "PDF"]],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
