<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Confidence Intervals for \(\mu\) | Introduction to Statistical Methodology, Second Edition</title>
  <meta name="description" content="Chapter 5 Confidence Intervals for \(\mu\) | Introduction to Statistical Methodology, Second Edition" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Confidence Intervals for \(\mu\) | Introduction to Statistical Methodology, Second Edition" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="dereksonderegger/570" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Confidence Intervals for \(\mu\) | Introduction to Statistical Methodology, Second Edition" />
  
  
  

<meta name="author" content="Derek L. Sonderegger &amp; Robert Buscaglia" />


<meta name="date" content="2020-08-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="4-sampling-distribution-of-barx.html"/>
<link rel="next" href="6-hypothesis-tests-for-the-mean-of-a-population.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html"><i class="fa fa-check"></i><b>1</b> Summary Statistics and Graphing</a><ul>
<li class="chapter" data-level="1.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#variable-types"><i class="fa fa-check"></i><b>1.1</b> Variable Types</a><ul>
<li class="chapter" data-level="1.1.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#categorical"><i class="fa fa-check"></i><b>1.1.1</b> Categorical</a></li>
<li class="chapter" data-level="1.1.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#numerical"><i class="fa fa-check"></i><b>1.1.2</b> Numerical</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#randomization-and-sampling"><i class="fa fa-check"></i><b>1.2</b> Randomization and Sampling</a><ul>
<li class="chapter" data-level="1.2.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#sampling-techniques"><i class="fa fa-check"></i><b>1.2.1</b> Sampling Techniques</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#graphical-summaries"><i class="fa fa-check"></i><b>1.3</b> Graphical Summaries</a><ul>
<li class="chapter" data-level="1.3.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#barchartsbarplots-univariate---categorical"><i class="fa fa-check"></i><b>1.3.1</b> Barcharts/Barplots (Univariate - Categorical)</a></li>
<li class="chapter" data-level="1.3.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#histogram-univariate---numerical"><i class="fa fa-check"></i><b>1.3.2</b> Histogram (Univariate - Numerical)</a></li>
<li class="chapter" data-level="1.3.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#boxplot-bivariate---categorical-vs-numerical"><i class="fa fa-check"></i><b>1.3.3</b> Boxplot (Bivariate - Categorical vs Numerical)</a></li>
<li class="chapter" data-level="1.3.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#scatterplot-bivariate---numerical-vs-numerical"><i class="fa fa-check"></i><b>1.3.4</b> Scatterplot (Bivariate - Numerical vs Numerical)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#measures-of-centrality"><i class="fa fa-check"></i><b>1.4</b> Measures of Centrality</a><ul>
<li class="chapter" data-level="1.4.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#mean"><i class="fa fa-check"></i><b>1.4.1</b> Mean</a></li>
<li class="chapter" data-level="1.4.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#median"><i class="fa fa-check"></i><b>1.4.2</b> Median</a></li>
<li class="chapter" data-level="1.4.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#mode"><i class="fa fa-check"></i><b>1.4.3</b> Mode</a></li>
<li class="chapter" data-level="1.4.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#examples"><i class="fa fa-check"></i><b>1.4.4</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#measures-of-spread"><i class="fa fa-check"></i><b>1.5</b> Measures of Spread</a><ul>
<li class="chapter" data-level="1.5.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#range"><i class="fa fa-check"></i><b>1.5.1</b> Range</a></li>
<li class="chapter" data-level="1.5.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#inter-quartile-range-iqr"><i class="fa fa-check"></i><b>1.5.2</b> Inter-Quartile Range (IQR)</a></li>
<li class="chapter" data-level="1.5.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#variance"><i class="fa fa-check"></i><b>1.5.3</b> Variance</a></li>
<li class="chapter" data-level="1.5.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#standard-deviation"><i class="fa fa-check"></i><b>1.5.4</b> Standard Deviation</a></li>
<li class="chapter" data-level="1.5.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#coefficient-of-variation"><i class="fa fa-check"></i><b>1.5.5</b> Coefficient of Variation</a></li>
<li class="chapter" data-level="1.5.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#empirical-rules"><i class="fa fa-check"></i><b>1.5.6</b> Empirical Rules</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#shape"><i class="fa fa-check"></i><b>1.6</b> Shape</a><ul>
<li class="chapter" data-level="1.6.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#symmetry"><i class="fa fa-check"></i><b>1.6.1</b> Symmetry</a></li>
<li class="chapter" data-level="1.6.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#unimodal-or-multi-modal"><i class="fa fa-check"></i><b>1.6.2</b> Unimodal or Multi-modal</a></li>
<li class="chapter" data-level="1.6.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#skew"><i class="fa fa-check"></i><b>1.6.3</b> Skew</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>1.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-probability.html"><a href="2-probability.html"><i class="fa fa-check"></i><b>2</b> Probability</a><ul>
<li class="chapter" data-level="2.1" data-path="2-probability.html"><a href="2-probability.html#introduction-to-set-theory"><i class="fa fa-check"></i><b>2.1</b> Introduction to Set Theory</a><ul>
<li class="chapter" data-level="2.1.1" data-path="2-probability.html"><a href="2-probability.html#composition-of-events"><i class="fa fa-check"></i><b>2.1.1</b> Composition of events</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2-probability.html"><a href="2-probability.html#probability-rules"><i class="fa fa-check"></i><b>2.2</b> Probability Rules</a><ul>
<li class="chapter" data-level="2.2.1" data-path="2-probability.html"><a href="2-probability.html#simple-rules"><i class="fa fa-check"></i><b>2.2.1</b> Simple Rules</a></li>
<li class="chapter" data-level="2.2.2" data-path="2-probability.html"><a href="2-probability.html#conditional-probability"><i class="fa fa-check"></i><b>2.2.2</b> Conditional Probability</a></li>
<li class="chapter" data-level="2.2.3" data-path="2-probability.html"><a href="2-probability.html#summary-of-probability-rules"><i class="fa fa-check"></i><b>2.2.3</b> Summary of Probability Rules</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-probability.html"><a href="2-probability.html#discrete-random-variables"><i class="fa fa-check"></i><b>2.3</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="2-probability.html"><a href="2-probability.html#introduction-to-discrete-random-variables"><i class="fa fa-check"></i><b>2.3.1</b> Introduction to Discrete Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-probability.html"><a href="2-probability.html#common-discrete-distributions"><i class="fa fa-check"></i><b>2.4</b> Common Discrete Distributions</a><ul>
<li class="chapter" data-level="2.4.1" data-path="2-probability.html"><a href="2-probability.html#binomial-distribution"><i class="fa fa-check"></i><b>2.4.1</b> Binomial Distribution</a></li>
<li class="chapter" data-level="2.4.2" data-path="2-probability.html"><a href="2-probability.html#poisson-distribution"><i class="fa fa-check"></i><b>2.4.2</b> Poisson Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="2-probability.html"><a href="2-probability.html#continuous-random-variables"><i class="fa fa-check"></i><b>2.5</b> Continuous Random Variables</a><ul>
<li class="chapter" data-level="2.5.1" data-path="2-probability.html"><a href="2-probability.html#uniform01-distribution"><i class="fa fa-check"></i><b>2.5.1</b> Uniform(0,1) Distribution</a></li>
<li class="chapter" data-level="2.5.2" data-path="2-probability.html"><a href="2-probability.html#exponential-distribution"><i class="fa fa-check"></i><b>2.5.2</b> Exponential Distribution</a></li>
<li class="chapter" data-level="2.5.3" data-path="2-probability.html"><a href="2-probability.html#normal-distribution"><i class="fa fa-check"></i><b>2.5.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="2.5.4" data-path="2-probability.html"><a href="2-probability.html#standardizing"><i class="fa fa-check"></i><b>2.5.4</b> Standardizing</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="2-probability.html"><a href="2-probability.html#r-quick-reference"><i class="fa fa-check"></i><b>2.6</b> R Quick Reference</a></li>
<li class="chapter" data-level="2.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>2.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html"><i class="fa fa-check"></i><b>3</b> Confidence Intervals via Bootstrapping</a><ul>
<li class="chapter" data-level="3.1" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#theory-of-bootstrapping"><i class="fa fa-check"></i><b>3.1</b> Theory of Bootstrapping</a></li>
<li class="chapter" data-level="3.2" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#conducting-a-bootstrap"><i class="fa fa-check"></i><b>3.2</b> Conducting a Bootstrap</a></li>
<li class="chapter" data-level="3.3" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#quantile-based-confidence-intervals"><i class="fa fa-check"></i><b>3.3</b> Quantile-based Confidence Intervals</a></li>
<li class="chapter" data-level="3.4" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#additional-examples"><i class="fa fa-check"></i><b>3.4</b> Additional Examples</a></li>
<li class="chapter" data-level="3.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html"><i class="fa fa-check"></i><b>4</b> Sampling Distribution of <span class="math inline">\(\bar{X}\)</span></a><ul>
<li class="chapter" data-level="4.1" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#enlightening-example"><i class="fa fa-check"></i><b>4.1</b> Enlightening Example</a></li>
<li class="chapter" data-level="4.2" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#mathematical-details"><i class="fa fa-check"></i><b>4.2</b> Mathematical details</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#probability-rules-for-expectations-and-variances"><i class="fa fa-check"></i><b>4.2.1</b> Probability Rules for Expectations and Variances</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#mean-and-variance-of-the-sample-mean"><i class="fa fa-check"></i><b>4.2.2</b> Mean and Variance of the Sample Mean</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#distribution-of-barx"><i class="fa fa-check"></i><b>4.3</b> Distribution of <span class="math inline">\(\bar{X}\)</span></a></li>
<li class="chapter" data-level="4.4" data-path="4-sampling-distribution-of-barx.html"><a href="4-sampling-distribution-of-barx.html#central-limit-theorem"><i class="fa fa-check"></i><b>4.4</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="4.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html"><i class="fa fa-check"></i><b>5</b> Confidence Intervals for <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="5.1" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html#asymptotic-result-sigma-known"><i class="fa fa-check"></i><b>5.1</b> Asymptotic result (<span class="math inline">\(\sigma\)</span> known)</a></li>
<li class="chapter" data-level="5.2" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html#asymptotoic-result-sigma-unknown"><i class="fa fa-check"></i><b>5.2</b> Asymptotoic result (<span class="math inline">\(\sigma\)</span> unknown)</a></li>
<li class="chapter" data-level="5.3" data-path="5-confidence-intervals-for-mu.html"><a href="5-confidence-intervals-for-mu.html#sample-size-selection"><i class="fa fa-check"></i><b>5.3</b> Sample Size Selection</a></li>
<li class="chapter" data-level="5.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html"><i class="fa fa-check"></i><b>6</b> Hypothesis Tests for the mean of a population</a><ul>
<li class="chapter" data-level="6.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#writing-hypotheses"><i class="fa fa-check"></i><b>6.1</b> Writing Hypotheses</a><ul>
<li class="chapter" data-level="6.1.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>6.1.1</b> Null and alternative hypotheses</a></li>
<li class="chapter" data-level="6.1.2" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#error"><i class="fa fa-check"></i><b>6.1.2</b> Error</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#conducting-a-hypothesis-test-for-mu"><i class="fa fa-check"></i><b>6.2</b> Conducting a Hypothesis Test for <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#why-should-hypotheses-use-mu-and-not-barx"><i class="fa fa-check"></i><b>6.2.1</b> Why should hypotheses use <span class="math inline">\(\mu\)</span> and not <span class="math inline">\(\bar{x}\)</span>?</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#a-note-on-calculating-p-values"><i class="fa fa-check"></i><b>6.2.2</b> A note on calculating p-values</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="3-confidence-intervals-via-bootstrapping.html"><a href="3-confidence-intervals-via-bootstrapping.html#additional-examples"><i class="fa fa-check"></i><b>6.3</b> Additional Examples</a></li>
<li class="chapter" data-level="6.4" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#p-values-vs-cutoff-values"><i class="fa fa-check"></i><b>6.4</b> P-values vs cutoff values</a></li>
<li class="chapter" data-level="6.5" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#running-a-t-test-in-r"><i class="fa fa-check"></i><b>6.5</b> Running a t-test in R</a></li>
<li class="chapter" data-level="6.6" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>6.6</b> Type I and Type II Errors</a><ul>
<li class="chapter" data-level="6.6.1" data-path="6-hypothesis-tests-for-the-mean-of-a-population.html"><a href="6-hypothesis-tests-for-the-mean-of-a-population.html#power-and-sample-size-selection"><i class="fa fa-check"></i><b>6.6.1</b> Power and Sample Size Selection</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>6.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> Two-Sample Hypothesis Tests and Confidence Intervals</a><ul>
<li class="chapter" data-level="7.1" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#difference-in-means-between-two-groups"><i class="fa fa-check"></i><b>7.1</b> Difference in means between two groups</a><ul>
<li class="chapter" data-level="7.1.1" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#inference-via-resampling"><i class="fa fa-check"></i><b>7.1.1</b> Inference via resampling</a></li>
<li class="chapter" data-level="7.1.2" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#inference-via-asymptotic-results-unequal-variance-assumption"><i class="fa fa-check"></i><b>7.1.2</b> Inference via asymptotic results (unequal variance assumption)</a></li>
<li class="chapter" data-level="7.1.3" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#inference-via-asymptotic-results-equal-variance-assumption"><i class="fa fa-check"></i><b>7.1.3</b> Inference via asymptotic results (equal variance assumption)</a></li>
<li class="chapter" data-level="7.1.4" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#additional-example"><i class="fa fa-check"></i><b>7.1.4</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#difference-in-means-between-two-groups-paired-data"><i class="fa fa-check"></i><b>7.2</b> Difference in means between two groups: Paired Data</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-two-sample-hypothesis-tests-and-confidence-intervals.html"><a href="7-two-sample-hypothesis-tests-and-confidence-intervals.html#additional-example-1"><i class="fa fa-check"></i><b>7.2.1</b> Additional Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html"><i class="fa fa-check"></i><b>8</b> Testing Model Assumptions</a><ul>
<li class="chapter" data-level="8.1" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#testing-normality"><i class="fa fa-check"></i><b>8.1</b> Testing Normality</a><ul>
<li class="chapter" data-level="8.1.1" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#visual-inspection---qqplots"><i class="fa fa-check"></i><b>8.1.1</b> Visual Inspection - QQplots</a></li>
<li class="chapter" data-level="8.1.2" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#tests-for-normality"><i class="fa fa-check"></i><b>8.1.2</b> Tests for Normality</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#testing-equal-variance"><i class="fa fa-check"></i><b>8.2</b> Testing Equal Variance</a><ul>
<li class="chapter" data-level="8.2.1" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#visual-inspection"><i class="fa fa-check"></i><b>8.2.1</b> Visual Inspection</a></li>
<li class="chapter" data-level="8.2.2" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#tests-for-equal-variance"><i class="fa fa-check"></i><b>8.2.2</b> Tests for Equal Variance</a></li>
<li class="chapter" data-level="8.2.3" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#symmetry-of-the-f-distribution"><i class="fa fa-check"></i><b>8.2.3</b> Symmetry of the F-distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#power-of-the-f-test"><i class="fa fa-check"></i><b>8.3</b> Power of the F-test</a></li>
<li class="chapter" data-level="8.4" data-path="8-testing-model-assumptions.html"><a href="8-testing-model-assumptions.html#theoretical-distribution-vs-bootstrap"><i class="fa fa-check"></i><b>8.4</b> Theoretical distribution vs bootstrap</a></li>
<li class="chapter" data-level="8.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html"><i class="fa fa-check"></i><b>9</b> Analysis of Variance (ANOVA)</a><ul>
<li class="chapter" data-level="9.1" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#model"><i class="fa fa-check"></i><b>9.1</b> Model</a></li>
<li class="chapter" data-level="9.2" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#theory"><i class="fa fa-check"></i><b>9.2</b> Theory</a><ul>
<li class="chapter" data-level="9.2.1" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#anova-table"><i class="fa fa-check"></i><b>9.2.1</b> Anova Table</a></li>
<li class="chapter" data-level="9.2.2" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#anova-using-simple-vs-complex-models."><i class="fa fa-check"></i><b>9.2.2</b> ANOVA using Simple vs Complex models.</a></li>
<li class="chapter" data-level="9.2.3" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#parameter-estimates-and-confidence-intervals"><i class="fa fa-check"></i><b>9.2.3</b> Parameter Estimates and Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#anova-in-r"><i class="fa fa-check"></i><b>9.3</b> Anova in R</a></li>
<li class="chapter" data-level="9.4" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#multiple-comparisons"><i class="fa fa-check"></i><b>9.4</b> Multiple comparisons</a></li>
<li class="chapter" data-level="9.5" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#different-model-representations"><i class="fa fa-check"></i><b>9.5</b> Different Model Representations</a><ul>
<li class="chapter" data-level="9.5.1" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#theory-1"><i class="fa fa-check"></i><b>9.5.1</b> Theory</a></li>
<li class="chapter" data-level="9.5.2" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#model-representations-in-r"><i class="fa fa-check"></i><b>9.5.2</b> Model Representations in R</a></li>
<li class="chapter" data-level="9.5.3" data-path="9-analysis-of-variance-anova.html"><a href="9-analysis-of-variance-anova.html#implications-on-the-anova-table"><i class="fa fa-check"></i><b>9.5.3</b> Implications on the ANOVA table</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>9.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="10-regression.html"><a href="10-regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a><ul>
<li class="chapter" data-level="10.1" data-path="10-regression.html"><a href="10-regression.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>10.1</b> Pearson’s Correlation Coefficient</a></li>
<li class="chapter" data-level="10.2" data-path="10-regression.html"><a href="10-regression.html#model-theory"><i class="fa fa-check"></i><b>10.2</b> Model Theory</a><ul>
<li class="chapter" data-level="10.2.1" data-path="10-regression.html"><a href="10-regression.html#anova-interpretation"><i class="fa fa-check"></i><b>10.2.1</b> Anova Interpretation</a></li>
<li class="chapter" data-level="10.2.2" data-path="10-regression.html"><a href="10-regression.html#confidence-intervals-vs-prediction-intervals"><i class="fa fa-check"></i><b>10.2.2</b> Confidence Intervals vs Prediction Intervals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="10-regression.html"><a href="10-regression.html#extrapolation"><i class="fa fa-check"></i><b>10.3</b> Extrapolation</a></li>
<li class="chapter" data-level="10.4" data-path="10-regression.html"><a href="10-regression.html#checking-model-assumptions"><i class="fa fa-check"></i><b>10.4</b> Checking Model Assumptions</a></li>
<li class="chapter" data-level="10.5" data-path="10-regression.html"><a href="10-regression.html#common-problems"><i class="fa fa-check"></i><b>10.5</b> Common Problems</a><ul>
<li class="chapter" data-level="10.5.1" data-path="10-regression.html"><a href="10-regression.html#influential-points"><i class="fa fa-check"></i><b>10.5.1</b> Influential Points</a></li>
<li class="chapter" data-level="10.5.2" data-path="10-regression.html"><a href="10-regression.html#transformations"><i class="fa fa-check"></i><b>10.5.2</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>10.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html"><i class="fa fa-check"></i><b>11</b> Contingency Tables</a><ul>
<li class="chapter" data-level="11.1" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html#expected-counts"><i class="fa fa-check"></i><b>11.1</b> Expected Counts</a></li>
<li class="chapter" data-level="11.2" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html#hypothesis-testing"><i class="fa fa-check"></i><b>11.2</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="11.3" data-path="11-contingency-tables.html"><a href="11-contingency-tables.html#rxc-tables"><i class="fa fa-check"></i><b>11.3</b> RxC tables</a></li>
<li class="chapter" data-level="11.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>11.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html"><i class="fa fa-check"></i>Appendix A : Resampling Linear Models</a><ul>
<li class="chapter" data-level="11.5" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#using-lm-for-many-analyses"><i class="fa fa-check"></i><b>11.5</b> Using <code>lm()</code> for many analyses</a><ul>
<li class="chapter" data-level="11.5.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#one-sample-t-tests"><i class="fa fa-check"></i><b>11.5.1</b> One-sample t-tests</a></li>
<li class="chapter" data-level="11.5.2" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#two-sample-t-tests"><i class="fa fa-check"></i><b>11.5.2</b> Two-sample t-tests</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#creating-simulated-data"><i class="fa fa-check"></i><b>11.6</b> Creating Simulated Data</a><ul>
<li class="chapter" data-level="11.6.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#observational-studies-vs-designed-experiments"><i class="fa fa-check"></i><b>11.6.1</b> Observational Studies vs Designed Experiments</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#confidence-interval-types"><i class="fa fa-check"></i><b>11.7</b> Confidence Interval Types</a><ul>
<li class="chapter" data-level="11.7.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#normal-intervals"><i class="fa fa-check"></i><b>11.7.1</b> Normal intervals</a></li>
<li class="chapter" data-level="11.7.2" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#percentile-intervals"><i class="fa fa-check"></i><b>11.7.2</b> Percentile intervals</a></li>
<li class="chapter" data-level="11.7.3" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#basic-intervals"><i class="fa fa-check"></i><b>11.7.3</b> Basic intervals</a></li>
<li class="chapter" data-level="11.7.4" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#towards-bias-corrected-and-accelerated-intervals-bca"><i class="fa fa-check"></i><b>11.7.4</b> Towards bias-corrected and accelerated intervals (BCa)</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#bootstrap-confidence-intervals-in-r"><i class="fa fa-check"></i><b>11.8</b> Bootstrap Confidence Intervals in R</a><ul>
<li class="chapter" data-level="11.8.1" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#using-carboot-function"><i class="fa fa-check"></i><b>11.8.1</b> Using <code>car::Boot()</code> function</a></li>
<li class="chapter" data-level="11.8.2" data-path="appendix-a-resampling-linear-models.html"><a href="appendix-a-resampling-linear-models.html#using-the-boot-package"><i class="fa fa-check"></i><b>11.8.2</b> Using the <code>boot</code> package</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>11.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-b-alternative-bootstrap-code.html"><a href="appendix-b-alternative-bootstrap-code.html"><i class="fa fa-check"></i>Appendix B : Alternative Bootstrap Code</a><ul>
<li class="chapter" data-level="" data-path="appendix-b-alternative-bootstrap-code.html"><a href="appendix-b-alternative-bootstrap-code.html#mosaic-package"><i class="fa fa-check"></i>Mosaic Package</a></li>
<li class="chapter" data-level="" data-path="appendix-b-alternative-bootstrap-code.html"><a href="appendix-b-alternative-bootstrap-code.html#base-r-code"><i class="fa fa-check"></i>Base R Code</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Methodology, Second Edition</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="confidence-intervals-for-mu" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Confidence Intervals for <span class="math inline">\(\mu\)</span></h1>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="5-confidence-intervals-for-mu.html#cb110-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb110-2"><a href="5-confidence-intervals-for-mu.html#cb110-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb110-3"><a href="5-confidence-intervals-for-mu.html#cb110-3"></a></span>
<span id="cb110-4"><a href="5-confidence-intervals-for-mu.html#cb110-4"></a><span class="co"># Set default behavior of ggplot2 graphs to be black/white theme</span></span>
<span id="cb110-5"><a href="5-confidence-intervals-for-mu.html#cb110-5"></a><span class="kw">theme_set</span>(<span class="kw">theme_bw</span>())</span></code></pre></div>
<div id="asymptotic-result-sigma-known" class="section level2">
<h2><span class="header-section-number">5.1</span> Asymptotic result (<span class="math inline">\(\sigma\)</span> known)</h2>
<p>We know that our sample mean <span class="math inline">\(\bar{x}\)</span>, should be close to the population mean <span class="math inline">\(\mu\)</span>. So when giving a region of values for <span class="math inline">\(\mu\)</span> that are consistent with the observed data, we would expect our CI formula to be something like <span class="math inline">\(\left(\bar{x}-d,\;\bar{x}+d\right)\)</span> for some value <span class="math inline">\(d\)</span>. That value of <span class="math inline">\(d\)</span> should be small if our sample size is big, representing our faith that a large amount of data should result in a statistic that is very close to the true value of <span class="math inline">\(\mu\)</span>. Recall that if our data <span class="math inline">\(X_{i}\sim N\left(\mu,\,\sigma^{2}\right)\)</span> or our sample size was large enough, then we know</p>
<p><span class="math display">\[\bar{X}\sim N\left(\mu,\,\;\sigma_{\bar{X}}^{2}=\frac{\sigma^{2}}{n}\right)\]</span>
or is approximately so. Doing a little re-arranging, we see that
<span class="math display">\[\frac{\bar{X}-\mu}{\left(\frac{\sigma}{\sqrt{n}}\right)}\sim N\left(0,1\right)\]</span></p>
<p>So if we take the 0.025 and 0.975 quantiles of the normal distribution, which are <span class="math inline">\(z_{0.025}=-1.96\)</span> and <span class="math inline">\(z_{0.975}=1.96\)</span>, we could write
<span class="math display">\[\begin{aligned}0.95	
    &amp;=	P\left[ -1.96\le\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}\le1.96 \right] \\
	  &amp;=	P\left[ -1.96\left(\frac{\sigma}{\sqrt{n}}\right)\le\bar{X}-\mu\le1.96\left(\frac{\sigma}{\sqrt{n}}\right) \right] \\
    &amp;=	P\left[ \bar{X}-1.96\left(\frac{\sigma}{\sqrt{n}}\right)\le\mu\le\bar{X}+1.96\left(\frac{\sigma}{\sqrt{n}}\right) \right]
    \end{aligned}\]</span>
Which suggests that a reasonable 95% Confidence Interval for <span class="math inline">\(\mu\)</span> is <span class="math display">\[\bar{x}\pm1.96\left(\frac{\sigma}{\sqrt{n}}\right)\]</span>
In general for a <span class="math inline">\(\left(1-\alpha\right)\cdot100\%\)</span> confidence interval, we would use the formula <span class="math inline">\(\bar{x}\pm z_{1-\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right)\)</span>. Notice that I could write the formula using <span class="math inline">\(z_{\alpha/2}\)</span> instead of <span class="math inline">\(z_{1-\alpha/2}\)</span> because the normal distribution is symmetric about 0 and we are subtracting and adding the same quantity to <span class="math inline">\(\bar{x}\)</span>.</p>
<p>The interpretation of a confidence interval is that over repeated sampling, <span class="math inline">\(100(1-\alpha)\%\)</span> of the resulting intervals will contain the population mean <span class="math inline">\(\mu\)</span>
but we don’t know if the interval we have actually observed is one of the good intervals that contains the mean <span class="math inline">\(\mu\)</span> or not. Because this is quite the mouthful, we will say “we are <span class="math inline">\(100\left(1-\alpha\right)\%\)</span> confident that the observed interval contains the mean <span class="math inline">\(\mu\)</span>.”</p>
<p><strong>Example:</strong> Suppose a bottling facility has a machine that supposedly fills bottles to 300 milliliters (ml) and is known to have a standard deviation of <span class="math inline">\(\sigma=3\)</span> ml. However, the machine occasionally gets out of calibration and might be consistently overfilling or under-filling bottles. To discover if the machine is calibrated correctly, we take a random sample of <span class="math inline">\(n=40\)</span> bottles and observe the mean amount filled was <span class="math inline">\(\bar{x}=299\)</span> ml. We calculate a <span class="math inline">\(95\%\)</span> confidence interval (CI) to be
<span class="math display">\[\begin{aligned} \bar{x}	&amp;\pm	z_{1-\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right)\\
                   299	  &amp;\pm	1.96\left(\frac{3}{\sqrt{40}}\right) \\
                   299	  &amp;\pm	0.93 \end{aligned}\]</span>
and conclude that we are <span class="math inline">\(95\%\)</span> confident that the that the true mean fill amount is in <span class="math inline">\(\left[298.07,299.93\right]\)</span> and that the machine has likely drifted off calibration.</p>
</div>
<div id="asymptotoic-result-sigma-unknown" class="section level2">
<h2><span class="header-section-number">5.2</span> Asymptotoic result (<span class="math inline">\(\sigma\)</span> unknown)</h2>
<p>It is unrealistic to expect that we know the population variance <span class="math inline">\(\sigma^{2}\)</span> but do not know the population mean <span class="math inline">\(\mu\)</span>. So in calculations that involve <span class="math inline">\(\sigma\)</span>, we want to use the sample standard deviation <span class="math inline">\(s\)</span> instead.</p>
<p>Our previous results about confidence intervals assumed that <span class="math inline">\(\bar{X}\sim N\left(\mu,\frac{\sigma^{2}}{n}\right)\)</span>
(or is approximately so) and therefore <span class="math display">\[\frac{\bar{X}-\mu}{\sqrt{\frac{\sigma^{2}}{n}}}\sim N\left(0,1\right)\]</span>
I want to just replace <span class="math inline">\(\sigma^{2}\)</span> with <span class="math inline">\(S^{2}\)</span> but the sample variance <span class="math inline">\(S^{2}\)</span> is also a random variable and incorporating it into the standardization function might affect the distribution. <span class="math display">\[\frac{\bar{X}-\mu}{\sqrt{\frac{S^{2}}{n}}}\sim\;???\]</span>
Unfortunately this substitution of <span class="math inline">\(S^{2}\)</span> for <span class="math inline">\(\sigma^{2}\)</span> comes with a cost and this quantity is not normally distributed. Instead it has a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom. However as the sample size increases and <span class="math inline">\(S^{2}\)</span> becomes a more reliable estimator of <span class="math inline">\(\sigma^{2}\)</span>, this penalty should become smaller.</p>
<p><img src="05_ConfidenceIntervals_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The <span class="math inline">\(t\)</span>-distribution is often call “Student’s t-distribution” is named after <a href="http://en.wikipedia.org/wiki/William_Sealy_Gosset">William Gosset</a> who worked at Guinness Brewing and did work with small sample sizes in both the brewery and at the farms that supplied the barley. Because Guinness prevented its employees from publishing any of their work, he published under the pseudonym “Student”.</p>
<p>Notice that as the sample size increases, the t-distribution gets closer and closer to the normal distribution. From here on out, we will use the following standardization formula:
<span class="math display">\[\frac{\bar{X}-\mu}{\frac{S}{\sqrt{n}}}\sim\;t_{n-1}\]</span>
and emphasize that this formula is valid if the sample observations came from a population with a normal distribution or if the sample size is large enough for the Central Limit Theorem to imply that <span class="math inline">\(\bar{X}\)</span> is approximately normally distributed.</p>
<p>Substituting the sample standard deviation into the confidence interval formula, we also substitute a t-quantile for the standard normal quantile. We will denote <span class="math inline">\(t_{n-1}^{1-\alpha/2}\)</span> as the <span class="math inline">\(1-\alpha/2\)</span> quantile of a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-1\)</span> degrees of freedom. Therefore we will use the following formula for the calculation of <span class="math inline">\(100\left(1-\alpha\right)\%\)</span> confidence intervals for the mean <span class="math inline">\(\mu\)</span>:
<span class="math display">\[\bar{x}\pm t_{n-1}^{1-\alpha/2}\left(\frac{s}{\sqrt{n}}\right)\]</span></p>
<p>Notation: We will be calculating confidence intervals for the rest of the course and it is useful to recognize the skeleton of a confidence interval formula. The basic form is always the same
<span class="math display">\[Estimate\;\pm\,t_{df}^{1-\alpha/2}\,\,Standard\,Error\left(\,Estimate\,\right)\]</span>
In our current problem, <span class="math inline">\(\bar{x}\)</span> is our estimate of <span class="math inline">\(\mu\)</span> and the estimated standard deviation (which is commonly called the standard error) is <span class="math inline">\(s/\sqrt{n}\)</span> and the appropriate degrees of freedom are <span class="math inline">\(df=n-1\)</span>.</p>
<p><strong>Example:</strong> Suppose we are interested in calculating a <span class="math inline">\(95\%\)</span> confidence interval for the mean weight of adult black bears. We collect a random sample of <span class="math inline">\(40\)</span> individuals (large enough for the CLT to kick in) and observe the following data:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="5-confidence-intervals-for-mu.html#cb111-1"></a>bears &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">weight =</span> </span>
<span id="cb111-2"><a href="5-confidence-intervals-for-mu.html#cb111-2"></a>   <span class="kw">c</span>(<span class="dv">306</span>, <span class="dv">446</span>, <span class="dv">276</span>, <span class="dv">235</span>, <span class="dv">295</span>, <span class="dv">302</span>, <span class="dv">374</span>, <span class="dv">339</span>, <span class="dv">624</span>, <span class="dv">266</span>,</span>
<span id="cb111-3"><a href="5-confidence-intervals-for-mu.html#cb111-3"></a>     <span class="dv">497</span>, <span class="dv">384</span>,  <span class="dv">429</span>, <span class="dv">497</span>, <span class="dv">224</span>, <span class="dv">157</span>, <span class="dv">248</span>, <span class="dv">349</span>, <span class="dv">388</span>, <span class="dv">391</span>,</span>
<span id="cb111-4"><a href="5-confidence-intervals-for-mu.html#cb111-4"></a>     <span class="dv">266</span>, <span class="dv">230</span>, <span class="dv">621</span>, <span class="dv">314</span>, <span class="dv">344</span>,  <span class="dv">413</span>, <span class="dv">267</span>, <span class="dv">380</span>, <span class="dv">225</span>, <span class="dv">418</span>,</span>
<span id="cb111-5"><a href="5-confidence-intervals-for-mu.html#cb111-5"></a>     <span class="dv">257</span>, <span class="dv">466</span>, <span class="dv">230</span>, <span class="dv">548</span>, <span class="dv">277</span>, <span class="dv">354</span>, <span class="dv">271</span>, <span class="dv">369</span>,  <span class="dv">275</span>, <span class="dv">272</span>))</span>
<span id="cb111-6"><a href="5-confidence-intervals-for-mu.html#cb111-6"></a>xbar &lt;-<span class="st"> </span><span class="kw">mean</span>(bears<span class="op">$</span>weight)</span>
<span id="cb111-7"><a href="5-confidence-intervals-for-mu.html#cb111-7"></a>s    &lt;-<span class="st"> </span><span class="kw">sd</span>(  bears<span class="op">$</span>weight)</span>
<span id="cb111-8"><a href="5-confidence-intervals-for-mu.html#cb111-8"></a><span class="kw">cbind</span>(xbar, s)</span></code></pre></div>
<pre><code>##       xbar        s
## [1,] 345.6 108.8527</code></pre>
<p>Notice that the data do not appear to come from a normal distribution, but a slightly heavier right tail. We’ll plot the histogram of data along with a normal distribution with the same mean and standard deviation as our data.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="5-confidence-intervals-for-mu.html#cb113-1"></a>normal.data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">weight=</span><span class="kw">seq</span>(<span class="dv">100</span>,<span class="dv">700</span>,<span class="dt">length=</span><span class="dv">1000</span>)) <span class="op">%&gt;%</span></span>
<span id="cb113-2"><a href="5-confidence-intervals-for-mu.html#cb113-2"></a><span class="st">  </span><span class="kw">mutate</span>( <span class="dt">y =</span> <span class="kw">dnorm</span>(weight, <span class="dt">mean=</span>xbar, <span class="dt">sd=</span>s))</span>
<span id="cb113-3"><a href="5-confidence-intervals-for-mu.html#cb113-3"></a><span class="kw">ggplot</span>() <span class="op">+</span></span>
<span id="cb113-4"><a href="5-confidence-intervals-for-mu.html#cb113-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y=</span><span class="st">&#39;density&#39;</span>) <span class="op">+</span></span>
<span id="cb113-5"><a href="5-confidence-intervals-for-mu.html#cb113-5"></a><span class="st">  </span><span class="kw">geom_area</span>( <span class="dt">data=</span>normal.data, <span class="kw">aes</span>(<span class="dt">x=</span>weight, <span class="dt">y=</span>y), <span class="dt">fill=</span><span class="st">&#39;light blue&#39;</span> ) <span class="op">+</span></span>
<span id="cb113-6"><a href="5-confidence-intervals-for-mu.html#cb113-6"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">data=</span>bears, <span class="kw">aes</span>(<span class="dt">x=</span>weight, <span class="dt">y=</span>..density..),</span>
<span id="cb113-7"><a href="5-confidence-intervals-for-mu.html#cb113-7"></a>                 <span class="dt">binwidth=</span><span class="dv">30</span>, <span class="dt">alpha=</span>.<span class="dv">6</span>)  </span></code></pre></div>
<p><img src="05_ConfidenceIntervals_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The observed sample mean is <span class="math inline">\(\bar{x}=345.6\)</span> pounds and a sample standard deviation <span class="math inline">\(s=108.8527\)</span> pounds. Because we want a <span class="math inline">\(95\%\)</span> confidence interval <span class="math inline">\(\alpha=0.05\)</span>. Using t-tables or the following R code</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="5-confidence-intervals-for-mu.html#cb114-1"></a><span class="kw">qt</span>(.<span class="dv">975</span>, <span class="dt">df=</span><span class="dv">39</span>)</span></code></pre></div>
<pre><code>## [1] 2.022691</code></pre>
<p>we find that <span class="math inline">\(t_{n-1}^{1-\alpha/2}=2.022691\)</span>. Therefore the <span class="math inline">\(95\%\)</span> confidence interval is
<span class="math display">\[\bar{x}	\pm	t_{n-1}^{1-\alpha/2}\left(\frac{s}{\sqrt{n}}\right)\]</span>
<span class="math display">\[345.6	\pm	2.022691\left(\frac{108.8527}{\sqrt{40}}\right)\]</span>
<span class="math display">\[345.6	\pm	34.8\]</span>
or <span class="math inline">\(\left(310.8, \, 380.4\right)\)</span> which is interpreted as “We are 95% confident that the true mean <span class="math inline">\(\mu\)</span> is in this interval” which is shorthand for “The process that resulted in this interval (taking a random sample, and then calculating an interval using the algorithm presented) will result in intervals such that 95% of them contain the mean <span class="math inline">\(\mu\)</span>, but we cannot know if this particular interval is one of the good ones or not.”</p>
<p>We can wonder how well this interval matches up with the interval we would have gotten if we had used the bootstrap method to create a confidence interval for <span class="math inline">\(\mu\)</span>. In this case, where the sample size <span class="math inline">\(n\)</span> is relatively large, the Central Limit Theorem is certainly working and the distribution of the sample mean certainly looks fairly normal.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="5-confidence-intervals-for-mu.html#cb116-1"></a>SampDist &lt;-<span class="st"> </span>mosaic<span class="op">::</span><span class="kw">do</span>(<span class="dv">10000</span>) <span class="op">*</span><span class="st"> </span>{</span>
<span id="cb116-2"><a href="5-confidence-intervals-for-mu.html#cb116-2"></a>  mosaic<span class="op">::</span><span class="kw">resample</span>(bears) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb116-3"><a href="5-confidence-intervals-for-mu.html#cb116-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">xbar=</span><span class="kw">mean</span>(weight)) </span>
<span id="cb116-4"><a href="5-confidence-intervals-for-mu.html#cb116-4"></a>}</span>
<span id="cb116-5"><a href="5-confidence-intervals-for-mu.html#cb116-5"></a><span class="kw">ggplot</span>(SampDist, <span class="kw">aes</span>(<span class="dt">x=</span>xbar, <span class="dt">y=</span>..density..)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb116-6"><a href="5-confidence-intervals-for-mu.html#cb116-6"></a><span class="st">  </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<p><img src="05_ConfidenceIntervals_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Grabbing the appropriate quantiles from the bootstrap estimate of the sampling distribution, we see that the bootstrap <span class="math inline">\(95\%\)</span> confidence interval matches up will with the confidence interval we obtained from asymptotic theory.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="5-confidence-intervals-for-mu.html#cb117-1"></a><span class="kw">quantile</span>( SampDist<span class="op">$</span>xbar, <span class="dt">probs=</span><span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>) )</span></code></pre></div>
<pre><code>##     2.5%    97.5% 
## 313.6244 380.7750</code></pre>
<p>Example: Assume that the percent of alcohol in casks of whiskey is normally distributed. From the last batch of casks produced, the brewer samples <span class="math inline">\(n=5\)</span> casks and wants to calculate a <span class="math inline">\(90\%\)</span> confidence interval for the mean percent alcohol in the latest batch produced. The sample mean was <span class="math inline">\(\bar{x}=55\)</span> percent and the sample standard deviation was <span class="math inline">\(s=4\)</span> percent.</p>
<p><span class="math display">\[\bar{x}	\pm	t_{n-1}^{1-\alpha/2}\left(\frac{s}{\sqrt{n}}\right)\]</span></p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="5-confidence-intervals-for-mu.html#cb119-1"></a><span class="kw">qt</span>( <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">.1</span><span class="op">/</span><span class="dv">2</span>, <span class="dt">df=</span><span class="dv">4</span>)  <span class="co"># 1-(.1)/2 = 1-.05 = .95</span></span></code></pre></div>
<pre><code>## [1] 2.131847</code></pre>
<p><span class="math display">\[55	\pm	2.13\left(\frac{4}{\sqrt{5}}\right)\]</span>
<span class="math display">\[55	\pm	3.8\]</span></p>
<p>Question: If we wanted a <span class="math inline">\(95\%\)</span> confidence interval, would it have been wider or narrower?</p>
<p>Question: If this interval is too wide to be useful, what could we do to make it smaller?</p>
</div>
<div id="sample-size-selection" class="section level2">
<h2><span class="header-section-number">5.3</span> Sample Size Selection</h2>
<p>Often a researcher is in the position of asking how many sample observations are necessary to achieve a specific width of confidence interval. Let the margin of error, which we denote <span class="math inline">\(ME\)</span>, be the half-width desired (so the confidence interval would be <span class="math inline">\(\bar{x}\pm ME\)</span>). So given the desired confidence level, and if we know <span class="math inline">\(\sigma\)</span>, then we can calculate the necessary number of samples to achieve a particular <span class="math inline">\(ME\)</span>. To do this calculation, we must also have some estimate of the population standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<p><span class="math display">\[ME=z_{1-\alpha/2}\left(\frac{\sigma}{\sqrt{n}}\right)\]</span>
and therefore
<span class="math display">\[n\approx\left[z_{1-\alpha/2}\left(\frac{\sigma}{ME}\right)\right]^{2}\]</span></p>
<p>Notice that because <span class="math display">\[n\propto\left[\frac{1}{ME}\right]^{2}\]</span> then if we want a margin of error that is twice as precise (i.e. the CI is half as wide) then we need to quadruple our sample size! Second, this result requires having some knowledge of <span class="math inline">\(\sigma\)</span>. We could acquire an estimate through:
1. a literature search
2. a pilot study
3. expert opinion.</p>
<p>A researcher is interested in estimating the mean weight of an adult elk in Yellowstone’s northern herd after the winter and wants to obtain a <span class="math inline">\(90\%\)</span> confidence interval with a half-width <span class="math inline">\(ME=10\)</span> pounds. Using prior collection data from the fall harvest (road side checks by game wardens), the researcher believes that <span class="math inline">\(\sigma=60\)</span> lbs is a reasonable standard deviation number to use.
<span class="math display">\[\begin{aligned}
  n	&amp;\approx	\left[ z_{0.95} \left(\frac{\sigma}{ME}\right)\right]^{2} \\
	  &amp;=	\left[1.645\left(\frac{60}{10}\right)\right]^{2}              \\
	  &amp;=	97.41  \end{aligned}\]</span></p>
<p>Notice that I don’t bother using the <span class="math inline">\(t\)</span>-distribution in this calculations because because I am assuming that <span class="math inline">\(\sigma\)</span> is known. While this is a horrible assumption, the difference between using a <span class="math inline">\(t\)</span> quantile instead of <span class="math inline">\(z\)</span> quantile is small and what really matters is how good the estimate of <span class="math inline">\(\sigma\)</span> is. As with many things, the quality of the input values is reflected in the quality of the output. Typically this sort of calculation is done with only a rough estimate of <span class="math inline">\(\sigma\)</span> and therefore I would subsequently regard the resulting sample size <span class="math inline">\(n\)</span> as an equally rough estimate.</p>
<p>We could be a bit more precise and use the <span class="math inline">\(t\)</span>-quantile, but because the degrees of freedom depend on <span class="math inline">\(n\)</span> as well, then we would have <span class="math inline">\(n\)</span> on both sides of the equation and there is no convenient algebraic solution to solving for <span class="math inline">\(n\)</span>. Later on we’ll use an R function that accounts for this, but for now we will use the rough approximation.</p>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">5.4</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li><p>An experiment is conducted to examine the susceptibility of root stocks of a variety of lemon trees to a specific larva. Forty of the plants are subjected to the larvae and examined after a fixed period of time. The response of interest is the logarithm of the number of larvae per gram of of root stock. For these 40 plants, the sample mean is <span class="math inline">\(\bar{x}=11.2\)</span> and the sample standard deviation is <span class="math inline">\(s=1.3\)</span>. Use these data to construct a <span class="math inline">\(90\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>, the mean susceptibility of lemon tree root stocks from which the sample was taken.</p></li>
<li><p>A social worker is interested in estimating the average length of time spent outside of prison for first offenders who later commit a second crime and are sent to prison again. A random sample of <span class="math inline">\(n=100\)</span> prison records in the count courthouse indicates that the average length of prison-free life between first and second offenses is <span class="math inline">\(4.2\)</span> years, with a standard deviation of <span class="math inline">\(1.1\)</span> years. Use this information to construct a <span class="math inline">\(95\%\)</span> confidence interval for <span class="math inline">\(\mu\)</span>, the average time between first and second offenses for all prisoners on record in the county courthouse.</p></li>
<li><p>A biologist wishes to estimate the effect of an antibiotic on the growth of a particular bacterium by examining the number of colony forming units (CFUs) per plate of culture when a fixed amount of antibiotic is applied. Previous experimentation with the antibiotic on this type of bacteria indicates that the standard deviation of CFUs is approximately <span class="math inline">\(4\)</span>. Using this information, determine the number of observations (i.e. cultures developed) necessary to calculate a <span class="math inline">\(99\%\)</span> confidence interval with a half-width of <span class="math inline">\(1\)</span>.</p></li>
<li><p>In the R package <code>Lock5Data</code>, the dataset <code>FloridaLakes</code> contains information about the mercury content of fish in 53 Florida lakes. For this question, we’ll be concerned with the average ppm of mercury in fish from those lakes which is encoded in the column <code>AvgMercury</code>.</p>
<ol style="list-style-type: lower-alpha">
<li>Using the bootstrapping method, calculate a 95% confidence interval for <span class="math inline">\(\mu\)</span>, the average ppm of mercury in fish in all Florida lakes.</li>
<li>Using the asymptotic approximations discussed in this chapter, calculate a 95% confidence interval for <span class="math inline">\(\mu\)</span>, the average ppm of mercury in fish in all Florida lakes.</li>
<li>Comment on the similarity of these two intervals.</li>
</ol></li>
<li><p>In the R package <code>Lock5Data</code>, the dataset Cereal contains nutrition information about a random sample of 30 cereals taken from an on-line nutrition information website (see the help file for the dataset to get the link). For this problem, we’ll consider the column Sugars which records the grams of sugar per cup.</p>
<ol style="list-style-type: lower-alpha">
<li>Using the bootstrapping method, calculate a 90% confidence interval for <span class="math inline">\(\mu\)</span>, the average grams of sugar per cup of all cereals listed on the website.</li>
<li>Using the asymptotic approximations discussed in this chapter, calculate a 90% confidence interval for <span class="math inline">\(\mu\)</span>, the average grams of sugar per cup of all cereals listed on this website.</li>
<li>Comment on the similarity of these two intervals.</li>
<li>We could easily write a little program (or pay an undergrad) to obtain the nutritional information about all the cereals on the website so the random sampling of 30 cereals is unnecessary. However, a bigger concern is that the website cereals aren’t representative of cereals Americans eat. Why? For example, consider what would happen if we added 30 new cereals that were very nutritious but were never sold.</li>
</ol></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="4-sampling-distribution-of-barx.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="6-hypothesis-tests-for-the-mean-of-a-population.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"],
"google": false,
"instapper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dereksonderegger/570/raw/master/05_ConfidenceIntervals.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": [["Statistical-Methods-I.pdf", "PDF"]],
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
